### ISSUE TITLE
Kerning concern.

### ISSUE THREAD

**Issue by afarlie** [GregFleming/Railway-Sans#2]
https://upload.wikimedia.org/wikipedia/commons/archive/9/9f/20170124103728%21Sameboat_temp_cc0.svg

Looking at the figures on this SVG, the kerning seemed a little odd compared to what might be expected.  

Is this present in the original typeface?

**Comment by GregFleming** [comment]
Odd. It should appear fine in print. What OS are you using, out of interest? For instance, some versions of OS X occasionally renders it oddly. 

I'll be releasing an updated version soon anyway and I will try to ensure this is ironed out.

**Comment by GregFleming** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2196447/23998942/b0824c3a-0a4e-11e7-9597-71a171a59d33.png)
It should look like this. I am assuming the SVG was using a version of the web font which it was having issues with.
